### ISSUE TITLE
安卓chrome浏览无法打开视频

### ISSUE THREAD

**Issue by AfterThreeYears** [axhello/douyu-vue#1]
试了好几次，就一次成功了，请问这是什么原因？我看代码那里就在src上放置了一个M3u8的url。

**Comment by axhello** [comment]
@AfterThreeYears 这情况我也不清楚诶~ 我是参考m.douyu.com的，用的api直接插入到video中，感觉可能是谷歌浏览器问题吧，我的魅蓝的自带浏览器完全可以播放。

**Comment by axhello** [comment]
@AfterThreeYears 目前不出问题应该可以播放了，但可能还有一点小问题，我看看能不能修复。。。
